[project]
name = "data-report"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "requests>=2.31",
    "python-dotenv>=1.0",
    "pygithub>=2.8.1",
]
